version: '2'
services:
    nginx:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/nginx.conf:/nginx.conf
            - ./docker/logs/nginx:/var/log/nginx
            - .:/var/www/html
        links:
            - php:php
        command: nginx -c /nginx.conf

    php:
        build:
            context: docker/php
            args:
                # Set here your timezone using one of this: https://php.net/manual/en/timezones.php
                timezone: 'Europe/Monaco'
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
        #links:
            # - "postgres:rdbms"
            # - "mariadb:rdbms"
        env_file:
            - ./docker/php/env
            # Comment non-used DBMS lines
            # If all DBMS are commented out, sqlite will be used as default
            # - ./docker/postgres/env
            # - ./docker/mariadb/env

    # postgres:
    #    image: postgres:11-alpine
    #    ports:
    #        - "5432:5432"
    #    volumes:
    #        - ./docker/data/pgsql:/var/lib/postgresql/data
    #    env_file:
    #        - ./docker/postgres/env

    # mariadb:
    #    image: mariadb:10
    #    ports:
    #        - "3306:3306"
    #    volumes:
    #        - ./docker/data/mariadb:/var/lib/mysql
    #    env_file:
    #        - ./docker/mariadb/env

    # rabbitmq:
    #     image: rabbitmq:3-management-alpine
    #     ports:
    #         - "15672:15672"

    redis:
        image: redis:4-alpine
        ports:
            - "6379:6379"
