preset: recommended

risky: false

enabled:

disabled:
  - align_double_arrow

finder:
  exclude:
    - "tests"
    - "storage"
    - "resources"
  name:
    - "*.php"
  not-name:
    - "*Stub.php"
  depth:
    - "< 3"