# @see https://www.tomasvotruba.cz/blog/2018/07/30/hidden-gems-of-php-packages-nette-utils/
services:
    Rector\Core\Rector\Function_\FunctionToStaticCallRector:
        $functionToStaticCall:
            # filesystem
            file_get_contents: ['Nette\Utils\FileSystem', 'read']
            unlink: ['Nette\Utils\FileSystem', 'delete']
            rmdir: ['Nette\Utils\FileSystem', 'delete']

    # strings
    Rector\Nette\Rector\NotIdentical\StrposToStringsContainsRector: null
    Rector\Nette\Rector\FuncCall\SubstrStrlenFunctionToNetteUtilsStringsRector: null
    Rector\Nette\Rector\Identical\StartsWithFunctionToNetteUtilsStringsRector: null

    Rector\Nette\Rector\FuncCall\PregMatchFunctionToNetteUtilsStringsRector: null
    Rector\Nette\Rector\FuncCall\PregFunctionToNetteUtilsStringsRector: null

    Rector\Nette\Rector\Identical\EndsWithFunctionToNetteUtilsStringsRector: null
    Rector\Nette\Rector\FuncCall\JsonDecodeEncodeToNetteUtilsJsonDecodeEncodeRector: null
    Rector\Nette\Rector\FuncCall\FilePutContentsToFileSystemWriteRector: null

    Rector\NetteUtilsCodeQuality\Rector\LNumber\ReplaceTimeNumberWithDateTimeConstantRector: null
