services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Rector\PSR4\:
        resource: '../src'
        exclude:
            - '../src/Rector/**/*Rector.php'
            - '../src/ValueObject/*'

    Rector\PSR4\Contract\PSR4AutoloadNamespaceMatcherInterface: '@Rector\PSR4\Composer\PSR4NamespaceMatcher'
