services:
    _defaults:
        public: true
        autowire: true

    Rector\NodeTypeResolver\:
        resource: '../src'
        exclude:
            - '../src/Contract/*'
            # "Type" is because the file is needed for PHPStan container only
            - '../src/PHPStan/TypeExtension/*'

    Rector\Core\Php\TypeAnalyzer: null
    Rector\Core\FileSystem\FilesFinder: null
    Rector\Core\PhpParser\Printer\BetterStandardPrinter: null
    Rector\Core\PhpParser\Node\BetterNodeFinder: null

    # PHPStan - this is the cleanest way to include another container
    # without injecting full container to Rector Symfony Continaer scope
    PHPStan\Reflection\ReflectionProvider:
        factory: ['@Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory', 'createReflectionProvider']

    PHPStan\Analyser\NodeScopeResolver:
        factory: ['@Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory', 'createNodeScopeResolver']

    PHPStan\Analyser\ScopeFactory:
        factory: ['@Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory', 'createScopeFactory']

    PHPStan\PhpDoc\TypeNodeResolver:
        factory: ['@Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory', 'createTypeNodeResolver']
