language: php
php:
  - 7.1
  - 7.2

script: "sh -c 'cd tests && php all_tests.php'"

notifications:
  recipients:
    - alessandro.fazzi@welaika.com
    - fabrizio.monti@welaika.com
    - federico.parodi@welaika.com
    - filippo.gangidino@welaika.com
    - matteo.piotto@welaika.com
    - stefano.pau@welaika.com
    - alessandra.cannata@welaika.com

deploy:
  provider: script
  script: bash deploy/deploy.sh
  on:
    tags: true
    branch: master
    php: 7.2
