services:
    Rector\CodingStyle\Rector\ClassMethod\ReturnArrayClassMethodToYieldRector:
        $methodsByType:
            PHPUnit\Framework\TestCase:
                - 'provide*'
                - 'dataProvider*'
