services:
    Rector\PHPUnit\Rector\MethodCall\RemoveExpectAnyFromMockRector: null
    Rector\PHPUnit\Rector\Class_\AddSeeTestAnnotationRector: null

    # [configurable]
    # Rector\PHPUnit\Rector\Class_\ArrayArgumentInTestToDataProviderRector: null
