services:
    Rector\PHPUnit\Rector\SpecificMethod\AssertNotOperatorRector: null
    Rector\PHPUnit\Rector\SpecificMethod\AssertComparisonToSpecificMethodRector: null
    Rector\PHPUnit\Rector\SpecificMethod\AssertTrueFalseToSpecificMethodRector: null
    Rector\PHPUnit\Rector\SpecificMethod\AssertSameBoolNullToSpecificMethodRector: null
    Rector\PHPUnit\Rector\SpecificMethod\AssertFalseStrposToContainsRector: null
    Rector\PHPUnit\Rector\SpecificMethod\AssertTrueFalseInternalTypeToSpecificMethodRector: null
    Rector\PHPUnit\Rector\SpecificMethod\AssertCompareToSpecificMethodRector: null
    Rector\PHPUnit\Rector\SpecificMethod\AssertIssetToSpecificMethodRector: null
    Rector\PHPUnit\Rector\SpecificMethod\AssertInstanceOfComparisonRector: null
    Rector\PHPUnit\Rector\SpecificMethod\AssertPropertyExistsRector: null
    Rector\PHPUnit\Rector\SpecificMethod\AssertRegExpRector: null
    Rector\PHPUnit\Rector\Foreach_\SimplifyForeachInstanceOfRector: null
