language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

sudo: false

services:
  - mysql
  - postgresql

addons:
  postgresql: "9.3"

before_script:
  # Set up Composer
  - composer self-update || true
  - composer global require hirak/prestissimo:~0.3
  - composer install --prefer-dist

script:
  ## Default install tests
  # PHPUnit
  - |
    export PHPUNIT_CMD="php -d memory_limit=2G ./vendor/bin/phpunit"
    if [[ $TRAVIS_EVENT_TYPE == "cron" && $TRAVIS_PHP_VERSION =~ ^7 ]] ; then
        composer require codeclimate/php-test-reporter:dev-master@dev
        $PHPUNIT_CMD --coverage-text --coverage-clover .coverage/clover/clover.xml --coverage-html .coverage/html/
        ./vendor/bin/test-reporter --coverage-report .coverage/clover/clover.xml
    else
        $PHPUNIT_CMD
    fi
  # Database platform
  - ./tests/scripts/dbsetup.sh
  - $PHPUNIT_CMD tests/phpunit/database/
  # Codeception
  - ./vendor/codeception/codeception/codecept build -vvv > /dev/null
  - ./vendor/codeception/codeception/codecept run --ext DotReporter
  # Deprecation checks
  - ./tests/scripts/deprecation-check.sh

# Cache directories
cache:
  directories:
    - $HOME/.composer/cache/files

dist: trusty
