# source: https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.0.md#upgrade-from-101-to-102

services:
    Rector\Core\Rector\ClassMethod\AddReturnTypeDeclarationRector:
        $typehintForMethodByClass:
            Sylius\Bundle\AdminApiBundle\Model\ClientManager:
                findClientByPublicId: '?Sylius\Bundle\AdminApiBundle\Model\ClientInterface'
