---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: Docs


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs on Pull Requests
  pull_request:

  # Runs on master Branch and Tags
  push:
    branches:
      - master
    tags:


# -------------------------------------------------------------------------------------------------
# What to run
# -------------------------------------------------------------------------------------------------
jobs:
  docs:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - build
          - linkcheck
          - linkcheck2

    name: "[Docs ${{ matrix.target }}]"
    steps:

      # ------------------------------------------------------------
      # Checkout repository
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Check documentation
        shell: bash
        run: |
          cd docs
          make ${TARGET}
        env:
          TARGET: ${{ matrix.target }}
