# @see http://www.phpspec.net/en/stable/manual/upgrading-to-phpspec-4.html
services:
    Rector\Core\Rector\ClassMethod\AddReturnTypeDeclarationRector:
        $typehintForMethodByClass:
            PhpSpec\ObjectBehavior:
                getMatchers: 'array'
