name: deploy-docs

on:
  push:
    paths:
        - 'docs/**'

jobs:
    deploy:

        runs-on: ubuntu-latest

        name: Deploy docs

        steps:
            - name: Netlify deploy
              uses: wei/curl@v1
              with:
                  args: -X POST -d {} ${{ secrets.NETLIFY_DEPLOY_URL }}?trigger_title=laravel-query-builder
