# See https://github.com/shopware/shopware/blob/5.5/UPGRADE-5.5.md
services:
    Rector\Core\Rector\MagicDisclosure\GetAndSetToMethodCallRector:
        $typeToMethodCalls:
            Enlight_View_Default:
                get: 'getAssign'
                set: 'assign'
            Enlight_Components_Session_Namespace:
                get: 'get'
                set: 'offsetSet'
            Shopware_Components_Config:
                get: 'offsetGet'
                set: 'offsetSet'

    Rector\Core\Rector\MagicDisclosure\UnsetAndIssetToMethodCallRector:
        $typeToMethodCalls:
            Enlight_Components_Session_Namespace:
                isset: 'offsetExists'
                unset: 'offsetUnset'
            Shopware_Components_Config:
                isset: 'offsetExists'
                unset: 'offsetUnset'
