# See https://github.com/shopware/shopware/blob/5.6/UPGRADE-5.6.md

imports:
    - { resource: '../elasticsearch-dsl/elasticsearch-dsl50.yaml' }

services:
    Rector\Renaming\Rector\MethodCall\RenameMethodCallRector:
        $oldToNewMethodsByClass:
            'Enlight_Controller_Response_Response':
                getHttpResponseCode: getStatusCode
                setHttpResponseCode: setStatusCode
                sendCookies: sendHeaders
                setBody: setContent
