services:
    # dependency-injection
    Rector\Core\Rector\Argument\ArgumentAdderRector:
        $positionWithDefaultValueByMethodNamesByClassTypes:
            # added default value
            Symfony\Component\DependencyInjection\ContainerBuilder:
                compile:
                    2:
                        name: '__unknown__'
                        default_value: 0
                addCompilerPass:
                    2:
                        name: 'priority'
                        default_value: 0
            Symfony\Component\DependencyInjection\Compiler\ServiceReferenceGraph:
                connect:
                    6:
                        name: 'weak'
                        default_value: false

    Rector\Symfony\Rector\Console\ConsoleExceptionToErrorEventConstantRector: null

    Rector\Renaming\Rector\Class_\RenameClassRector:
        $oldToNewClasses:
            # console
            'Symfony\Component\Console\Event\ConsoleExceptionEvent': 'Symfony\Component\Console\Event\ConsoleErrorEvent'

            # debug
            'Symfony\Component\Debug\Exception\ContextErrorException': 'ErrorException'

            # dependency-injection
            'Symfony\Component\DependencyInjection\DefinitionDecorator': 'Symfony\Component\DependencyInjection\ChildDefinition'

            # framework bundle
            'Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\AddConsoleCommandPass': 'Symfony\Component\Console\DependencyInjection\AddConsoleCommandPass'
            'Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\SerializerPass': 'Symfony\Component\Serializer\DependencyInjection\SerializerPass'
            'Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\FormPass': 'Symfony\Component\Form\DependencyInjection\FormPass'
            'Symfony\Bundle\FrameworkBundle\EventListener\SessionListener': 'Symfony\Component\HttpKernel\EventListener\SessionListener'
            'Symfony\Bundle\FrameworkBundle\EventListener\TestSessionListenr': 'Symfony\Component\HttpKernel\EventListener\TestSessionListener'
            'Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\ConfigCachePass': 'Symfony\Component\Config\DependencyInjection\ConfigCachePass'
            'Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\PropertyInfoPass': 'Symfony\Component\PropertyInfo\DependencyInjection\PropertyInfoPass'

    Rector\Renaming\Rector\MethodCall\RenameMethodRector:
        $oldToNewMethodsByClass:
            # dependency-injection
            'Symfony\Component\DependencyInjection\Container':
                isFrozen: 'isCompiled'
