services:
    Rector\Core\Rector\Argument\ArgumentRemoverRector:
        $positionsByMethodNameByClassType:
            Symfony\Component\Yaml\Yaml:
                parse:
                    2:
                        - 'Symfony\Component\Yaml\Yaml::PARSE_KEYS_AS_STRINGS'

    Rector\Symfony\Rector\ClassMethod\MergeMethodAnnotationToRouteAnnotationRector: null
