services:
    # Yaml::parse('file.yml')   →   Yaml::parse(file_get_contents('file.yml'))
    Rector\Symfony\Rector\Yaml\ParseFileRector: null

    #  UrlGenerator constants change
    # https://github.com/symfony/symfony/commit/912fc4de8fd6de1e5397be4a94d39091423e5188
    Rector\Core\Rector\Argument\ArgumentDefaultValueReplacerRector:
        $replacesByMethodAndTypes:
            Symfony\Component\Routing\Generator\UrlGeneratorInterface:
                generate:
                    2:
                        -
                            before: true
                            after: Symfony\Component\Routing\Generator\UrlGeneratorInterface::ABSOLUTE_URL
                        -
                            before: false
                            after: Symfony\Component\Routing\Generator\UrlGeneratorInterface::ABSOLUTE_PATH
                        -
                            before: 'relative'
                            after: Symfony\Component\Routing\Generator\UrlGeneratorInterface::RELATIVE_PATH
                        -
                            before: 'network'
                            after: Symfony\Component\Routing\Generator\UrlGeneratorInterface::NETWORK_PATH
