services:
    Rector\Symfony\Rector\Validator\ConstraintUrlOptionRector: null
    Rector\Symfony\Rector\Form\FormIsValidRector: null
    Rector\Symfony\Rector\Form\StringFormTypeToClassRector: null
    Rector\Symfony\Rector\VarDumper\VarDumperTestTraitMethodArgsRector: null
    Rector\Symfony\Rector\DependencyInjection\ContainerBuilderCompileEnvArgumentRector: null

    Rector\Symfony\Rector\Process\ProcessBuilderInstanceRector: null
    Rector\Symfony\Rector\Process\ProcessBuilderGetProcessRector: null

    Rector\Renaming\Rector\Class_\RenameClassRector:
        $oldToNewClasses:
            'Symfony\Component\Validator\Tests\Constraints\AbstractConstraintValidatorTest': 'Symfony\Component\Validator\Test\ConstraintValidatorTestCase'
            'Symfony\Component\Process\ProcessBuilder': 'Symfony\Component\Process\Process'
