branches:
  only:
    - master
language: node_js
node_js:
  - "8"
  - "10"
cache:
  directories:
    - "node_modules"
before_install:
  - cp .env.example .env
install:
  - npm install
before_script:
  - npm run build
  - npm run pages:build-404-html
script:
  - npm run lint --no-fix
  - npm run test:unit
