services:
    # rename class, rename extends, remove include __DIR__, remove (new TestCase())->run())
    Rector\NetteTesterToPHPUnit\Rector\Class_\NetteTesterClassToPHPUnitClassRector: null

    # Assert::true → self::assertTrue() | PHPUnit\Framework\Assert::assertTrue()
    Rector\NetteTesterToPHPUnit\Rector\StaticCall\NetteAssertToPHPUnitAssertRector: null

    # Some.phpt → SomeTest.php
    Rector\NetteTesterToPHPUnit\Rector\RenameTesterTestToPHPUnitToTestFileRector: null
