services:
    _defaults:
        autowire: true
        public: true

    Rector\BetterPhpDocParser\:
        resource: '../src'
        exclude:
            - '../src/ValueObject/*'
            - '../src/*/*Info.php'
            - '../src/*Info.php'
            - '../src/Attributes/Ast/PhpDoc/*'
            - '../src/PhpDocNode/*'

    PHPStan\PhpDocParser\Lexer\Lexer: null
    PHPStan\PhpDocParser\Parser\TypeParser: null
    PHPStan\PhpDocParser\Parser\ConstExprParser: null

    PHPStan\PhpDocParser\Parser\PhpDocParser:
        alias: 'Rector\BetterPhpDocParser\PhpDocParser\BetterPhpDocParser'

    Doctrine\Common\Annotations\Reader:
        alias: 'Rector\DoctrineAnnotationGenerated\ConstantPreservingAnnotationReader'
