services:
    # properties
    Rector\Doctrine\Rector\Property\AddUuidAnnotationsToIdPropertyRector: null
    Rector\Doctrine\Rector\Property\RemoveTemporaryUuidColumnPropertyRector: null
    Rector\Doctrine\Rector\Property\RemoveTemporaryUuidRelationPropertyRector: null

    # methods
    Rector\Doctrine\Rector\ClassMethod\ChangeGetIdTypeToUuidRector: null
    Rector\Doctrine\Rector\ClassMethod\ChangeSetIdTypeToUuidRector: null
