services:
    Rector\Doctrine\Rector\MethodCall\ChangeSetIdToUuidValueRector: null
    Rector\Doctrine\Rector\MethodCall\ChangeGetUuidMethodCallToGetIdRector: null
    Rector\Doctrine\Rector\ClassMethod\ChangeReturnTypeOfClassMethodWithGetIdRector: null
    Rector\Doctrine\Rector\Identical\ChangeIdenticalUuidToEqualsMethodCallRector: null

    # add Uuid type declarations
    Rector\TypeDeclaration\Rector\ClassMethod\AddMethodCallBasedParamTypeRector: null
    Rector\TypeDeclaration\Rector\ClassMethod\AddArrayReturnDocTypeRector: null
