services:
    Rector\Php74\Rector\Property\TypedPropertyRector: null

    Rector\Renaming\Rector\Function_\RenameFunctionRector:
        $oldFunctionToNewFunction:
            # https://wiki.php.net/rfc/deprecations_php_7_4#the_real_type
            is_real: 'is_float'
            # https://wiki.php.net/rfc/deprecations_php_7_4#apache_request_headers_function
            apache_request_headers: 'getallheaders'
            hebrevc: ['nl2br', 'hebrev']

    Rector\Php74\Rector\FuncCall\ArrayKeyExistsOnPropertyRector: null
    Rector\Php74\Rector\FuncCall\FilterVarToAddSlashesRector: null
    Rector\Php74\Rector\StaticCall\ExportToReflectionFunctionRector: null
    Rector\Php74\Rector\MagicConstClass\ClassConstantToSelfClassRector: null
    Rector\Php74\Rector\FuncCall\GetCalledClassToStaticClassRector: null
    Rector\Php74\Rector\FuncCall\MbStrrposEncodingArgumentPositionRector: null
    Rector\Php74\Rector\Double\RealToFloatTypeCastRector: null
    Rector\Php74\Rector\Assign\NullCoalescingOperatorRector: null
    Rector\Php74\Rector\Function_\ReservedFnFunctionRector: null
    Rector\Php74\Rector\Closure\ClosureToArrowFunctionRector: null
    Rector\Php74\Rector\FuncCall\ArraySpreadInsteadOfArrayMergeRector: null
    Rector\Php74\Rector\LNumber\AddLiteralSeparatorToNumberRector: null
    Rector\Php74\Rector\MethodCall\ChangeReflectionTypeToStringToGetNameRector: null
    Rector\Php74\Rector\Property\RestoreDefaultNullToNullableTypePropertyRector: null
