services:
    Rector\Php71\Rector\BinaryOp\IsIterableRector: null

    Rector\Php71\Rector\Name\ReservedObjectRector:
        $reservedKeywordsToReplacements:
            Object: 'BaseObject'

    Rector\Php71\Rector\TryCatch\MultiExceptionCatchRector: null
    Rector\Php71\Rector\Assign\AssignArrayToStringRector: null
    Rector\Php71\Rector\FuncCall\CountOnNullRector: null
    Rector\Php71\Rector\FuncCall\RemoveExtraParametersRector: null
    Rector\Php71\Rector\BinaryOp\BinaryOpBetweenNumberAndStringRector: null
    Rector\Php71\Rector\List_\ListToArrayDestructRector: null
