imports:
    - { resource: "../database-migration/mysql-to-mysqli.yaml" }

services:
    Rector\Php70\Rector\FunctionLike\Php4ConstructorRector: null
    Rector\Php70\Rector\Ternary\TernaryToNullCoalescingRector: null
    Rector\Php70\Rector\FuncCall\RandomFunctionRector: null
    Rector\Php70\Rector\FunctionLike\ExceptionHandlerTypehintRector: null
    Rector\Php70\Rector\FuncCall\MultiDirnameRector: null
    Rector\Php70\Rector\List_\ListSplitStringRector: null
    Rector\Php70\Rector\List_\EmptyListRector: null

    # be careful, run this just once, since it can keep swapping order back and forth
    Rector\Php70\Rector\List_\ListSwapArrayOrderRector: null

    Rector\Php70\Rector\FuncCall\CallUserMethodRector : null
    Rector\Php70\Rector\FuncCall\EregToPregMatchRector: null
    Rector\Php70\Rector\Switch_\ReduceMultipleDefaultSwitchRector: null
    Rector\Php70\Rector\Ternary\TernaryToSpaceshipRector: null
    Rector\Php70\Rector\If_\IfToSpaceshipRector: null
    Rector\Php70\Rector\StaticCall\StaticCallOnNonStaticToInstanceCallRector: null
    Rector\Php70\Rector\MethodCall\ThisCallOnStaticMethodToStaticCallRector: null

    Rector\Php70\Rector\Break_\BreakNotInLoopOrSwitchToReturnRector: null
    Rector\Php70\Rector\FuncCall\RenameMktimeWithoutArgsToTimeRector: null
    Rector\Php70\Rector\FuncCall\NonVariableToVariableOnFunctionCallRector: null
