services:
    Rector\Php73\Rector\BinaryOp\IsCountableRector: null
    Rector\Php73\Rector\FuncCall\ArrayKeyFirstLastRector: null
    Rector\Php73\Rector\FuncCall\SensitiveDefineRector: null
    Rector\Php73\Rector\ConstFetch\SensitiveConstantNameRector: null
    Rector\Php73\Rector\String_\SensitiveHereNowDocRector: null

    # https://wiki.php.net/rfc/deprecations_php_7_3
    Rector\Renaming\Rector\Function_\RenameFunctionRector:
        $oldFunctionToNewFunction:
            image2wbmp: 'imagewbmp'
            mbregex_encoding: 'mb_regex_encoding'
            mbereg: 'mb_ereg'
            mberegi: 'mb_eregi'
            mbereg_replace: 'mb_ereg_replace'
            mberegi_replace: 'mb_eregi_replace'
            mbsplit: 'mb_split'
            mbereg_match: 'mb_ereg_match'
            mbereg_search: 'mb_ereg_search'
            mbereg_search_pos: 'mb_ereg_search_pos'
            mbereg_search_regs: 'mb_ereg_search_regs'
            mbereg_search_init: 'mb_ereg_search_init'
            mbereg_search_getregs: 'mb_ereg_search_getregs'
            mbereg_search_getpos: 'mb_ereg_search_getpos'

    Rector\Php73\Rector\FuncCall\StringifyStrNeedlesRector: null
    Rector\Php73\Rector\FuncCall\JsonThrowOnErrorRector: null
    Rector\Php73\Rector\FuncCall\RegexDashEscapeRector: null
    Rector\Php73\Rector\FuncCall\RemoveMissingCompactVariableRector: null
