services:
    Rector\Php72\Rector\Each\WhileEachToForeachRector: null
    Rector\Php72\Rector\Each\ListEachRector: null
    Rector\Php72\Rector\Each\ReplaceEachAssignmentWithKeyCurrentRector: null

    Rector\Php72\Rector\Unset_\UnsetCastRector: null
    Rector\Php72\Rector\ConstFetch\BarewordStringRector: null

    Rector\Renaming\Rector\Function_\RenameFunctionRector:
        $oldFunctionToNewFunction:
            jpeg2wbmp: 'imagecreatefromjpeg' # and imagewbmp
            png2wbmp: 'imagecreatefrompng' # or imagewbmp
            # http://php.net/manual/en/migration72.deprecated.php#migration72.deprecated.gmp_random-function
            gmp_random: 'gmp_random_bits' # or gmp_random_range
            read_exif_data: 'exif_read_data'

    Rector\Php72\Rector\FuncCall\GetClassOnNullRector: null
    Rector\Php72\Rector\FuncCall\IsObjectOnIncompleteClassRector: null
    Rector\Php72\Rector\FuncCall\ParseStrWithResultArgumentRector: null
    Rector\Php72\Rector\FuncCall\StringsAssertNakedRector: null
    Rector\Php72\Rector\FuncCall\CreateFunctionToAnonymousFunctionRector: null
    Rector\Php72\Rector\FuncCall\StringifyDefineRector: null
