services:
    Rector\Php80\Rector\FunctionLike\UnionTypesRector: null
    Rector\Php80\Rector\NotIdentical\StrContainsRector: null
    Rector\Php80\Rector\Identical\StrStartsWithRector: null
    Rector\Php80\Rector\Identical\StrEndsWithRector: null
    Rector\Php80\Rector\Class_\StringableForToStringRector: null
    Rector\Php80\Rector\Class_\AnnotationToAttributeRector: null
    Rector\Php80\Rector\FuncCall\ClassOnObjectRector: null
    Rector\Php80\Rector\Ternary\GetDebugTypeRector: null
    Rector\Php80\Rector\FuncCall\TokenGetAllToObjectRector: null
    Rector\Php80\Rector\Catch_\RemoveUnusedVariableInCatchRector: null
