---
engines:
  phpmd:
    enabled: true
    config:
      rulesets: "phpmd.xml.dist"
  phpcs:
    enabled: true
    config:
      ruleset: "phpcs.xml.dist"

exclude_paths:
  - 'ext/**'
  - 'prototypes/**'
