parameters:
    # path to load services from
    symfony_container_xml_path: ''

services:
    _defaults:
        public: true
        autowire: true

    Rector\Symfony\:
        resource: '../src'
        exclude:
            - '../src/Rector/**/*Rector.php'
            - '../src/Exception/*'
            - '../src/ValueObject/*'
            - '../src/PhpDocParser/Ast/PhpDoc/*'
