services:
    _defaults:
        public: true
        autowire: true

    Rector\Core\:
        resource: '../src'
        exclude:
            - '../src/Rector/**/*Rector.php'
            - '../src/Testing/PHPUnit/*'
            - '../src/RectorDefinition/*'
            - '../src/Exception/*'
            - '../src/DependencyInjection/CompilerPass/*'
            - '../src/DependencyInjection/Loader/*'
            - '../src/HttpKernel/*'
            - '../src/ValueObject/*'

    Symfony\Component\Console\Application:
        alias: 'Rector\Core\Console\Application'

    Symfony\Component\Console\Descriptor\TextDescriptor: null

    # PhpParser - Parser
    PhpParser\ParserFactory: null
    PhpParser\BuilderFactory: null
    PhpParser\NodeVisitor\CloningVisitor:
    PhpParser\NodeFinder: null

    PhpParser\Parser:
        factory: ['@Rector\Core\PhpParser\Parser\NikicPhpParserFactory', 'create']

    PhpParser\Lexer:
        factory: ['@Rector\Core\PhpParser\Parser\LexerFactory', 'create']

    # value resolver
    Symfony\Component\Filesystem\Filesystem: null
    Symplify\PackageBuilder\Reflection\PrivatesAccessor: null

    Symplify\SmartFileSystem\Finder\FinderSanitizer: null
    Symplify\SmartFileSystem\FileSystemFilter: null

    Symplify\PackageBuilder\Parameter\ParameterProvider: null
    Symplify\PackageBuilder\Reflection\PrivatesCaller: null
    Symplify\PackageBuilder\Strings\StringFormatConverter: null

    OndraM\CiDetector\CiDetector: null

    Symfony\Component\EventDispatcher\EventDispatcherInterface: '@Rector\Core\EventDispatcher\AutowiredEventDispatcher'
