name: Validate Sets

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    validate_sets:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none

            -   run: composer install --no-progress --ansi

            # this is very slow, so it has to be in own workflow
            -   run: bin/rector validate-sets --ansi
