services:
    _defaults:
        autowire: true
        public: true

    Rector\CodingStyle\:
        resource: '../src'
        exclude:
            - '../src/Rector/**/*Rector.php'
            - '../src/ValueObject/*'
