parameters:
    project_directory: null

services:
    _defaults:
        public: true
        autowire: true

    Rector\FileSystemRector\:
        resource: '../src'
        exclude:
            - '../src/Rector/**/*Rector.php'
