services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Rector\PhpAttribute\:
        resource: '../src'
        exclude:
            - '../src/Contract/*'
            - '../src/ValueObject/*'
