services:
    # see https://stackoverflow.com/a/43495506/1348344
    Rector\Renaming\Rector\Class_\RenameClassRector:
        $oldToNewClasses:
            'Twig_Function_Node': 'Twig_SimpleFunction'
            'Twig_Function': 'Twig_SimpleFunction'
            'Twig_Filter': 'Twig_SimpleFilter'
            'Twig_Test': 'Twig_SimpleTest'
