services:
    Rector\Renaming\Rector\Class_\RenameClassRector:
        $oldToNewClasses:
            # see https://twig.symfony.com/doc/1.x/deprecated.html#filters
            'Twig_SimpleFilter': 'Twig_Filter'
            # see https://twig.symfony.com/doc/1.x/deprecated.html#functions
            'Twig_SimpleFunction': 'Twig_Function'
            # see https://github.com/bolt/bolt/pull/6596
            'Twig_SimpleTest': 'Twig_Test'
