# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
    type: upstream
    upstream: "app:http"
"https://www.{default}/":
    type: redirect
    to: "https://{default}/"
"https://{default}/.well-known/carddav":
    type: redirect
    to: "https://{default}/dav"
"https://{default}/.well-known/caldav":
    type: redirect
    to: "https://{default}/dav"
"https://{default}/.well-known/security.txt":
    type: redirect
    to: "https://{default}/security.txt"
