# source: https://book.cakephp.org/3.0/en/appendices/3-7-migration-guide.html

services:
    Rector\Renaming\Rector\MethodCall\RenameMethodRector:
        $oldToNewMethodsByClass:
            'Cake\Form\Form':
                'errors': 'getErrors'
            'Cake\Validation\Validation':
                cc: 'creditCard'
            'Cake\Filesystem\Folder':
                normalizePath: 'correctSlashFor'
            'Cake\Http\Client\Response':
                body: 'getStringBody'
            'Cake\Core\Plugin':
                unload: 'clear'

    Rector\Core\Rector\Property\PropertyToMethodRector:
        $perClassPropertyToMethods:
            'Cake\Http\Client\Response':
                body:
                    get: 'getStringBody'
                json:
                    get: 'getJson'
                xml:
                    get: 'getXml'
                cookies:
                    get: 'getCookies'
                code:
                    get: 'getStatusCode'
            'Cake\View\View':
                request:
                    get: 'getRequest'
                    set: 'setRequest'
                response:
                    get: 'getResponse'
                    set: 'setResponse'
                templatePath:
                    get: 'getTemplatePath'
                    set: 'setTemplatePath'
                template:
                    get: 'getTemplate'
                    set: 'setTemplate'
                layout:
                    get: 'getLayout'
                    set: 'setLayout'
                layoutPath:
                    get: 'getLayoutPath'
                    set: 'setLayoutPath'
                autoLayout:
                    get: 'enableAutoLayout'
                    set: 'isAutoLayoutEnabled'
                theme:
                    get: 'getTheme'
                    set: 'setTheme'
                subDir:
                    get: 'getSubDir'
                    set: 'setSubDir'
                plugin:
                    get: 'getPlugin'
                    set: 'setPlugin'
                name:
                    get: 'getName'
                    set: 'setName'
                elementCache:
                    get: 'getElementCache'
                    set: 'setElementCache'
                helpers:
                    get: 'helpers'

    Rector\Core\Rector\MethodCall\MethodCallToAnotherMethodCallWithArgumentsRector:
        $oldMethodsToNewMethodsWithArgsByType:
            'Cake\Database\Query':
                join: ['clause', ['join']]
                from: ['clause', ['from']]

    Rector\CakePHP\Rector\MethodCall\ModalToGetSetRector:
        $methodNamesByTypes:
            'Cake\Database\Connection':
                logQueries:
                    set: 'enableQueryLogging'
                    get: 'isQueryLoggingEnabled'
            'Cake\ORM\Association':
                className:
                    set: 'setClassName'
                    get: 'getClassName'

    Rector\CakePHP\Rector\Name\ChangeSnakedFixtureNameToCamelRector: null
