# https://github.com/EasyCorp/EasyAdminBundle/blob/master/UPGRADE-2.0.md
services:
    # first replace ->get("...") by constructor injection in every child of "EasyCorp\Bundle\EasyAdminBundle\AdminController"
    Rector\Symfony\Rector\FrameworkBundle\GetToConstructorInjectionRector:
        $getMethodAwareTypes:
            - 'EasyCorp\Bundle\EasyAdminBundle\AdminController'

    # then rename the "EasyCorp\Bundle\EasyAdminBundle\AdminController" class
    Rector\Renaming\Rector\Class_\RenameClassRector:
        $oldToNewClasses:
            'EasyCorp\Bundle\EasyAdminBundle\AdminController': 'EasyCorp\Bundle\EasyAdminBundle\EasyAdminController'
