service: app

provider:
    name: aws
    region: us-east-1
    runtime: provided

plugins:
    - ./vendor/bref/bref

functions:
    console:
        handler: bin/console # Replace by `artisan` if you are using Laravel
        description: ''
        timeout: 30 # in seconds
        layers:
            - ${bref:layer.php-73} # PHP
            - ${bref:layer.console} # The "console" layer

# Exclude files from deployment
package:
    exclude:
        - 'tests/**'
