services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Rector\Doctrine\:
        resource: '../src'
        exclude:
            - '../src/Rector/**/*Rector.php'

    Rector\Doctrine\Contract\Mapper\DoctrineEntityAndRepositoryMapperInterface:
        alias: 'Rector\Doctrine\Mapper\DefaultDoctrineEntityAndRepositoryMapper'
