language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
#  - hhvm

#matrix:
#  allow_failures:
#    - php: hhvm

services:
  - mysql

addons:
  hosts:
    - local.94cb.com
    - local-m.94cb.com
    - local-api.94cb.com

before_script:
  - chmod 777 -R ./
  - mysql -e "create database IF NOT EXISTS carbon;" -uroot
  - php -m
  - cd library
  - if [ $(phpenv version-name) != "5.4" ]; then composer install; fi
  - cd ../
  # for Install
  - php -S 0.0.0.0:8080 &
  # Using a Router Script for Test
  - php -S 0.0.0.0:8099 index.php &

script:
  - find ./ -type f -print0 | while read -d $'\0' file; do if [ "${file##*.}" = "php" ]; then echo "Check $file"; php -l $file; echo "";  echo ""; fi; done
  - php test-install.php
  - cd language
  - if [ $(phpenv version-name) != "5.4" ]; then php auto_translate.php; fi
  - cd ../
  - php test.php