language: php
dist: trusty
sudo: false

branches:
  except:
    - l10n_2.3
    - l10n_2.4

before_install:
  - cp .env.example .env

install:
  - travis_retry composer install --no-interaction --no-suggest

jobs:
  include:
#    - stage: Security check
#      script:
#        - phpenv config-rm xdebug.ini || true
#        - wget https://get.sensiolabs.org/security-checker.phar
#        - php security-checker.phar security:check ./composer.lock
#      php: 7.1
    - stage: Unit tests
      script:
        - phpenv config-rm xdebug.ini || true
        - vendor/bin/phpunit
      php: 7.1
    - stage: Unit tests
      script:
        - phpenv config-rm xdebug.ini || true
        - vendor/bin/phpunit
      php: 7.2
    - stage: Unit tests
      script:
        - phpenv config-rm xdebug.ini || true
        - vendor/bin/phpunit
      php: 7.3
    - stage: Code coverage
      script:
        - phpenv config-rm xdebug.ini || true
        - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
        - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
        - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
      php: 7.1
