# see: https://laravel.com/docs/5.1/upgrade
services:
    Rector\Renaming\Rector\Class_\RenameClassRector:
        $oldToNewClasses:
            'Illuminate\Validation\Validator': 'Illuminate\Contracts\Validation\Validator'
