# https://laravel-news.com/laravel-5-8-deprecates-string-and-array-helpers
# https://github.com/laravel/framework/pull/26898
imports:
    - { resource: 'static/array-str-functions-to-static-call.yaml'}

# see: https://laravel.com/docs/5.8/upgrade
services:
    Rector\Laravel\Rector\StaticCall\MinutesToSecondsInCacheRector: null

    Rector\Core\Rector\ClassMethod\AddReturnTypeDeclarationRector:
        $typehintForMethodByClass:
            Illuminate\Contracts\Cache\Repository:
                put: 'bool'
                forever: 'bool'
            Illuminate\Contracts\Cache\Store:
                put: 'bool'
                putMany: 'bool'
                forever: 'bool'

    Rector\Core\Rector\Property\RenamePropertyRector:
        $oldToNewPropertyByTypes:
            Illuminate\Routing\UrlGenerator:
                cachedSchema: 'cachedScheme'
