imports:
    # from https://github.com/laravel/framework/blob/5.8/src/Illuminate/Support/helpers.php to direct static calls
    - { resource: 'static/array-str-functions-to-static-call.yaml'}

services:
    Rector\Laravel\Rector\StaticCall\FacadeStaticCallToConstructorInjectionRector: null
    Rector\Laravel\Rector\StaticCall\RequestStaticValidateToInjectRector: null
    Rector\Laravel\Rector\FuncCall\HelperFunctionToConstructorInjectionRector: null

    Rector\Core\Rector\FuncCall\FunctionToNewRector:
        $functionToNew:
            collect: 'Illuminate\Support\Collection'
