# see https://laravel.com/docs/5.3/upgrade
services:
    Rector\Core\Rector\ClassLike\RemoveTraitRector:
        $traitsToRemove:
            - 'Illuminate\Foundation\Auth\Access\AuthorizesResources'
