# see: https://laravel.com/docs/5.7/upgrade
services:
    Rector\Core\Rector\Visibility\ChangeMethodVisibilityRector:
        $methodToVisibilityByClass:
            'Illuminate\Routing\Router':
                addRoute: 'public'
            'Illuminate\Contracts\Auth\Access\Gate':
                raw: 'public'

    Rector\Core\Rector\Argument\ArgumentAdderRector:
        $positionWithDefaultValueByMethodNamesByClassTypes:
            'Illuminate\Auth\Middleware\Authenticate':
                authenticate:
                    name: 'request'
            'Illuminate\Foundation\Auth\ResetsPasswords':
                sendResetResponse:
                    name: 'request'
                    type: 'Illuminate\Http\Illuminate\Http'
            'Illuminate\Foundation\Auth\SendsPasswordResetEmails':
                sendResetLinkResponse:
                    name: 'request'
                    type: 'Illuminate\Http\Illuminate\Http'

    Rector\Laravel\Rector\StaticCall\Redirect301ToPermanentRedirectRector: null

    Rector\Core\Rector\Argument\ArgumentRemoverRector:
        $positionsByMethodNameByClassType:
            'Illuminate\Foundation\Application':
                register:
                    1:
                        name: 'options'
