# see: https://laravel.com/docs/5.5/upgrade
services:
    Rector\Renaming\Rector\MethodCall\RenameMethodRector:
        $oldToNewMethodsByClass:
            'Illuminate\Console\Command':
                fire: 'handle'

    Rector\Core\Rector\Property\RenamePropertyRector:
        $oldToNewPropertyByTypes:
            'Illuminate\Database\Eloquent\Concerns\HasEvents':
                events: 'dispatchesEvents'
            'Illuminate\Database\Eloquent\Relations\Pivot':
                parent: 'pivotParent'

    Rector\Renaming\Rector\Class_\RenameClassRector:
        $oldToNewClasses:
            'Illuminate\Translation\LoaderInterface': 'Illuminate\Contracts\Translation\Loader'
