# see: https://laravel.com/docs/5.6/upgrade
services:
    Rector\Renaming\Rector\MethodCall\RenameMethodRector:
        $oldToNewMethodsByClass:
            'Illuminate\Validation\ValidatesWhenResolvedTrait':
                validate: 'validateResolved'
            'Illuminate\Contracts\Validation\ValidatesWhenResolved':
                validate: 'validateResolved'

    Rector\Core\Rector\Visibility\ChangeMethodVisibilityRector:
        $methodToVisibilityByClass:
            'Illuminate\Routing\Router':
                addRoute: 'public'
            'Illuminate\Contracts\Auth\Access\Gate':
                raw: 'public'
            'Illuminate\Database\Grammar':
                getDateFormat: 'public'
