language: php
php:
    - 5.6
    - 7.1
    - 7.2
    - 7.3
    - 7.4
matrix:
  allow_failures:
    - php: 5.6
#    - php: hhvm
# optionally specify a list of environments, for example to test different RDBMS
env:
    - DB=mysql

before_install:
    - composer self-update
    - composer dump-autoload

# execute any number of scripts before the test run, custom env's are available as variables

before_script:
    - travis_retry composer install
    - curl -sSfL -o ~/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

#  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS microweber_tests;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit 

# configure notifications (email, IRC, campfire etc)
notifications:
    rc: "irc.freenode.org#microweber"
branches:
    only:
        - master
        - dev
        - tests	
        - build