imports:
    - { resource: '../../packages/**/src/config/services.yml' }

services:
    _defaults:
        autowire: true

    # PSR-4 autodiscovery
    ApiGen\:
        resource: '../../src'
        exclude: '../../src/{Application/Command,Event,Exception}'

    # Filter Aware Latte Engine
    Latte\Engine:
        factory: ['@ApiGen\Latte\FiltersAwareLatteEngineFactory', 'create']

    # PHP Documentor
    phpDocumentor\Reflection\DocBlockFactory: ~
    phpDocumentor\Reflection\Types\ContextFactory: ~
    phpDocumentor\Reflection\FqsenResolver: ~
    phpDocumentor\Reflection\DocBlock\StandardTagFactory: ~
    phpDocumentor\Reflection\DocBlock\DescriptionFactory: ~
    phpDocumentor\Reflection\TypeResolver: ~

    # Source Code Highlighter
    FSHL\Output\Html: ~
    FSHL\Lexer\Php: ~
    FSHL\Highlighter:
        calls:
            - [setLexer, ['@FSHL\Lexer\Php']]

    # 3rd party services
    Symfony\Component\Console\Application:
        arguments: ["ApiGen", "Unknown Version"]
    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\EventDispatcher\EventDispatcher: ~
