rules:
    no_inheritdoc: ~
    avoid_repetetive_words: ~
    blank_line_after_directive: ~
    short_array_syntax: ~
    no_app_console: ~
    typo: ~
    replacement: ~
    composer_dev_option_not_at_the_end: ~
    yarn_dev_option_at_the_end: ~
    versionadded_directive_should_have_version: ~
    deprecated_directive_should_have_version: ~
    no_composer_req: ~
    no_php_open_tag_in_code_block_php_directive: ~
    no_blank_line_after_filepath_in_php_code_block: ~
    no_blank_line_after_filepath_in_yaml_code_block: ~
    no_blank_line_after_filepath_in_xml_code_block: ~
    no_blank_line_after_filepath_in_twig_code_block: ~
    php_prefix_before_bin_console: ~
    use_deprecated_directive_instead_of_versionadded: ~
    no_space_before_self_xml_closing_tag: ~
    no_explicit_use_of_code_block_php: ~
    ensure_order_of_code_blocks_in_configuration_block: ~
    american_english: ~
    valid_use_statements: ~
    lowercase_as_in_use_statements: ~
    ordered_use_statements: ~
    no_namespace_after_use_statements: ~
    correct_code_block_directive_based_on_the_content: ~
    max_blank_lines:
        max: 2
    replace_code_block_types: ~
    use_https_xsd_urls: ~
    blank_line_before_directive: ~
    extension_xlf_instead_of_xliff: ~
    valid_inline_highlighted_namespaces: ~
    indention: ~
    unused_links: ~
    yaml_instead_of_yml_suffix: ~
    extend_abstract_controller: ~
#    no_app_bundle: ~

    #   master
    versionadded_directive_major_version:
        major_version: 5

    versionadded_directive_min_version:
        min_version: '5.0'

    deprecated_directive_major_version:
        major_version: 5

    deprecated_directive_min_version:
        min_version: '5.0'

# do not report as violation
whitelist:
    regex:
        - '/FOSUserBundle(.*)\.yml/'
        - '/``.yml``/'
        - '/(.*)\.orm\.yml/' # currently DoctrineBundle only supports .yml
    lines:
        - 'in config files, so the old ``app/config/config_dev.yml`` goes to'
        - '#. The most important config file is ``app/config/services.yml``, which now is'
        - 'code in production without a proxy, it becomes trivially easy to abuse your'
        - '.. _`EasyDeployBundle`: https://github.com/EasyCorp/easy-deploy-bundle'
        - 'The bin/console Command'
        - '# username is your full Gmail or Google Apps email address'
        - '.. _`LDAP injection`: http://projects.webappsec.org/w/page/13246947/LDAP%20Injection'
        - '.. versionadded:: 0.21.0' # Encore
        - '.. versionadded:: 0.28.4' # Encore
        - '.. versionadded:: 2.4.0' # SwiftMailer
        - '.. versionadded:: 1.30' # Twig
        - '.. versionadded:: 1.35' # Twig
        - '.. versionadded:: 1.2' # MakerBundle
        - '.. versionadded:: 1.11' # MakerBundle
        - '.. versionadded:: 1.3' # MakerBundle
        - '.. versionadded:: 1.8' # MakerBundle
        - '.. versionadded:: 1.6' # Flex in setup/upgrade_minor.rst
        - '0 => 123' # assertion for var_dumper - components/var_dumper.rst
        - '1 => "foo"' # assertion for var_dumper - components/var_dumper.rst
        - '123,' # assertion for var_dumper - components/var_dumper.rst
        - '"foo",' # assertion for var_dumper - components/var_dumper.rst
        - '$var .= "Because of this `\xE9` octet (\\xE9),\n";'
        - "`Deploying Symfony 4 Apps on Heroku`_."
        - ".. _`Deploying Symfony 4 Apps on Heroku`: https://devcenter.heroku.com/articles/deploying-symfony4"
        - "//                  224, 165, 141, 224, 164, 164, 224, 165, 135])"
        - '.. versionadded:: 0.2' # MercureBundle
        - 'provides a ``loginUser()`` method to simulate logging in in your functional'
