---
passwordcheck:
  validators:
    required:
      message: PASSWORD.CONFIRM_CURRENT
email:
  validators:
    required:
      label: "&EMAIL"
      message: VALIDATE.REQUIRED
    length:
      label: "&EMAIL"
      min: 1
      max: 150
      message: VALIDATE.LENGTH_RANGE
    email:
      message: VALIDATE.INVALID_EMAIL
password:
  validators:
    length:
      label: "&PASSWORD"
      min: 12
      max: 100
      message: VALIDATE.LENGTH_RANGE
passwordc:
  validators:
    matches:
      field: password
      label: "&PASSWORD.CONFIRM"
      message: VALIDATE.PASSWORD_MISMATCH
    length:
      label: "&PASSWORD.CONFIRM"
      min: 12
      max: 100
      message: VALIDATE.LENGTH_RANGE
