services:
    Rector\Core\Rector\Architecture\DependencyInjection\ActionInjectionToConstructorInjectionRector: null
    Rector\Core\Rector\Architecture\DependencyInjection\ReplaceVariableByPropertyFetchRector: null
