services:
    # <> → !=
    Rector\Celebrity\Rector\NotEqual\CommonNotEqualRector: null

    Rector\Renaming\Rector\Function_\RenameFunctionRector:
        $oldFunctionToNewFunction:
            split: 'explode'
            join: 'implode'
            sizeof: 'count'

            # https://www.php.net/manual/en/aliases.php
            chop: 'rtrim'
            doubleval: 'floatval'
            gzputs: 'gzwrites'
            fputs: 'fwrite'
            ini_alter: 'ini_set'
            is_double: 'is_float'
            is_integer: 'is_int'
            is_long: 'is_int'
            is_real: 'is_float'
            is_writeable: 'is_writable'
            key_exists: 'array_key_exists'
            pos: 'current'
            strchr: 'strstr'
            # mb
            mbstrcut: 'mb_strcut'
            mbstrlen: 'mb_strlen'
            mbstrpos: 'mb_strpos'
            mbstrrpos: 'mb_strrpos'
            mbsubstr: 'mb_substr'

    # settype($value, 'int') → (int) $value
    Rector\Celebrity\Rector\FuncCall\SetTypeToCastRector: null

    # class { var $value; } → class { public $value; }
    Rector\Php52\Rector\Property\VarToPublicPropertyRector: null

    #  false or true → false || true
    #  false and true → false && true
    Rector\Celebrity\Rector\BooleanOp\LogicalToBooleanRector: null
