language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  matrix:
    - COMPOSER_VERSION=1
    - COMPOSER_VERSION=2
    - COMPOSER_VERSION=1 DEPENDENCIES=--prefer-lowest

cache:
  directories:
    - ~/.cache/composer

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - phpenv config-rm xdebug.ini
  - alias composer=composer\ --no-interaction && composer selfupdate --$COMPOSER_VERSION
  - |
      if [ $COMPOSER_VERSION -eq 1 ]; then
        composer global require hirak/prestissimo
      fi;

install:
  - travis_retry composer update --no-progress --profile --no-scripts --no-suggest $DEPENDENCIES

script:
   - bin/grumphp run

notifications:
  irc:
    skip_join: true
    channels:
      - chat.freenode.net#grumphp
