services:
    Rector\SOLID\Rector\If_\RemoveAlwaysElseRector: null
    Rector\SOLID\Rector\If_\ChangeNestedIfsToEarlyReturnRector: null
    Rector\SOLID\Rector\If_\ChangeIfElseValueAssignToEarlyReturnRector: null
